spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  datasource:
    url: jdbc:mysql://localhost:3306/statemachine?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ciao
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    log-request-details: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    from: devtestdevtest828117@tiscali.it
    host: smtp.tiscali.it
    port: 465
    protocol: smtp
    username: devtestdevtest828117@tiscali.it
    password: _DkW3bwVqWVh3vG
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
mail:
  smtp:
    starttls:
      enable: false
debug: true

app:
  jwtSecret: secret
  jwtExpirationInMs: 3600000

logging:
  level:
    org:
      springframework:
        web: DEBUG